on:
  push:
    branches:
      - master

env:
  BINARY_NAME: totp-from-uri

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-22.04
    env:
      TARGET: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - run: cargo build --release --target $TARGET
      - run: |
          mkdir package
          cp target/$TARGET/release/$BINARY_NAME package/

  build-linux-arm64:
    runs-on: ubuntu-22.04-arm
    env:
      TARGET: aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - run: cargo build --release --target $TARGET
      - run: |
          mkdir package
          cp target/$TARGET/release/totp-from-uri package/

  build-windows-x86_64:
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - run: cargo build --release --target $env:TARGET
        env:
          RUSTFLAGS: -C target-feature=+crt-static
      - run: |
          mkdir package
          cp target/$env:Target/release/$env:BINARY_NAME.exe package/

  build-macos:
    runs-on: macos-latest
    env:
      TARGET: aarch64-apple-darwin
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - run: cargo build --release --target $TARGET
      - run: |
          mkdir package
          cp target/$TARGET/release/$BINARY_NAME package/
